[package]
name = "termgui"
version = "0.0.1"
authors = ["Xirdus <xirdus@gmail.com>"]

[target.x86_64-pc-windows-gnu.dependencies]
kernel32-sys = ">=0.0.7"
winapi = ">=0.1.14"

[target.x86_64-unknown-linux-gnu.dependencies]
ncurses = "*"
